### ISSUE TITLE
Cobalt Server Update Request: Fix Video Download Error

### ISSUE THREAD

**Issue by afkarxyz** [nichind/pybalt#1]
Hi, please update the Cobalt server to version 10.4.3. There's an API update to fix the issue of some videos failing during downloads.

**Comment by afkarxyz** [comment]
When attempting to download audio for this video https://www.youtube.com/watch?v=8Ebqe2Dbzls, the message **"error.api.content.video.unavailable"** appears.

**Comment by nichind** [comment]
> When attempting to download audio for this video https://www.youtube.com/watch?v=8Ebqe2Dbzls, the message **"error.api.content.video.unavailable"** appears.

Video is region blocked, can't do anything about it. Now it would try to cycle trough public instances on this type of error, not sure that will be any help tho.
