### ISSUE TITLE
YouTube Download returns 0 byte file

### ISSUE THREAD

**Issue by ITZ-ZAID** [nichind/pybalt#2]
![IMG_20241216_100328](https://github.com/user-attachments/assets/a8fd51c4-1f11-4195-867d-4552c23d26ff)

**Comment by nichind** [comment]
Try changing the instance with `-i fetch`, and make sure you use the last version of pybalt

**Comment by nichind** [comment]
Updated pybalt to `2024.12.7`, now on zero-byte result it would try another instance from community list. Update with pip install pybalt -U
